### ISSUE TITLE
 should Migrate from legacy HTTP to HTTP v1

### ISSUE THREAD

**Issue by Roy-Mao** [decision-labs/fcm#50]
Apps using the FCM legacy HTTP API should consider migrating to the HTTP v1 API

For details:
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by sabman** [comment]
@prcongithub thanks can you add tests and create a PR?

**Comment by Alan-M-Thomaz** [comment]
Beware of the fact HTTP v1 does not support devices groups, nor multicast messages yet, wich would cause a big breaking change.

We can use both, legacy for those features, and V1 to the rest, but i don't think it a good idea.

**Comment by ChrisBr** [comment]
Is there anything we could help to bring this over the finishing line?

**Comment by sabman** [comment]
Out of date. Please try with the new version. closing for now.

**Comment by ostigley** [comment]
Hi there, thanks for providing this gem 👍 .

Just checking if this issue is on the road map at all? There are features in the HTTP v1 API that would be great to utilise (`analytics_label`, for example).

OR has it been integrated already?

Line 48 of the README implies yes, but checking the code it still looks like this gem is using the legacy api `/fcm/send`.  The readme#48 implies all of those options are available, but after some testing it would appear not to be the case.  Am I doing something wrong?  Here's my options block:


```
{
  'data': {
    'type': 'page',
    'path': @notification.path
  },
  'notification': {
    'click_action': 'FCM_PLUGIN_ACTIVITY',
    'title': @notification.title,
    'body': @notification.body,
    'image': @notification.image
  },
  'android': {
    'fcm_options': {
      'analytics_label': @notification.label
    }
  },
  'apns': {
    'fcm_options': {
      'analytics_label': @notification.label
    }
  }
}
```

**Comment by sabman** [comment]
@ostigley you are correct it seems we are still using the old API. I was under the impression @prcongithub 's PR addressed that but I think it didn't. I am reopening this. Will add it to the road map

**Comment by JerakRus** [comment]
Hello everyone, are there any updates on this issue?

**Comment by sabman** [comment]
Hi all I'll need some help with this. I am open to having a paired programming session with someone who is using this day to day to help me close this. If you know the relevant portion of the FCM docs we can have a paired programming session in the coming days. Just send me a meeting request at https://calendly.com/sabman

**Comment by sabman** [comment]
All I'd like to make some time to pair with someone interested in migrating from the legacy API. to this end I've created a doodle to try to find a time that people interested can remotely pair. If you are interested in helping please let me know your availability here: https://doodle.com/poll/7gmqmyk62qq6z7sm

**Comment by f3z0** [comment]
So unfortunately after upgrading to Flutter 2.0 and the latest flutterfire messages being sent from the legacy HTTP API is no longer coming through unless there is a notification attached. That's a bummer as we aren't able to use this gem any more. Since we are just needing to push one very specific type of message to topics we just wrote a few lines code for that very specific use case as a work-around but I wanted to share it here in hopes someone has the interest / time to pick up the torch here or if someone else finds themselves needing a work-around to get them to HTTP v1 in a bind.

Here is the gist: https://gist.github.com/f3z0/a09ae96b55ba95e117a596fb7e67e279

Feel free to ping me with any questions. Thank you 🙏

**Comment by sabman** [comment]
@f3z0 thanks for this looks useful. I presume we will need to cut a new major version if do this since it will break existing functionality unless people have created their credentials correctly and made them available to the library. 

I'll make a start on it next week if anyone has any further thoughts beside's the gist from @f3z0 please let me know below.

> Here is the gist: https://gist.github.com/f3z0/a09ae96b55ba95e117a596fb7e67e279

**Comment by vadimeremeev** [comment]
Hi everyone, I've incorporated gist from above to FCM gem here: https://github.com/decision-labs/fcm/pull/91
Happy to discuss what else needs to be done if that approach will work
Vadim

**Comment by iamdeveloper-lopez** [comment]
Hello guys, when will this feature be available ?

**Comment by sabman** [comment]
@iamdeveloper-lopez I am going to release a new version which includes the `send_v1` method for HTTP v1 shortly. However, we will need to refactor this in the future to use name spaces as this is a little untidy.

**Comment by sabman** [comment]
https://github.com/decision-labs/fcm/releases/tag/v1.0.5
